{% set name = "orderly-set" %}
{% set version = "5.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/orderly_set-{{ version }}.tar.gz
  sha256: 52a18b86aaf3f5d5a498bbdb27bf3253a4e5c57ab38e5b7a56fa00115cd28448

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - orderly_set
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/seperman/orderly-set
  summary: Orderly set
  license: MIT
  license_file: MIT-LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
