context:
  name: orderly-set
  version: "5.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/orderly_set-${{ version }}.tar.gz
  sha256: c8ff5ba824abe4eebcbbdd3f646ff3648ad0dd52239319d90056d8d30b6cccdd

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - orderly_set
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Orderly set
  license: MIT
  license_file: MIT-LICENSE
  homepage: https://github.com/seperman/orderly-set

extra:
  recipe-maintainers:
    - synapticarbors
